### ISSUE TITLE
user_key and user_pseudo_id

### ISSUE THREAD

**Issue by ivan-toriya** [Velir/dbt-ga4#104]
I think it's useful to add `user_key` in `fct_ga4__sessions` alongside with `user_pseudo_id`
E.g. I want to join `dim_ga4__users` to have some info about the user on the session level.

What do you think about that? I can make a PR.

**Comment by adamribaudo-velir** [comment]
@ivan-toriya can you confirm that you're looking at the `main` branch? We recently merged #99 which deprecated the concept of a `user_key`. Now `fct_ga4__sessions` can be joined to `dim_ga4__user_pseudo_ids` and then there's a mapping table, `stg_ga4__user_id_mapping`,  between user_id and user_pseudo_id

**Comment by ivan-toriya** [comment]
My bad, I was looking into the latest version in dbt package hub.
When are you planning next release?

**Comment by adamribaudo-velir** [comment]
No worries! No immediate plans for a release, but you can always pull the latest code into your dbt project by following the instructions in the readme.
