### ISSUE TITLE
Problem to add custom parameters

### ISSUE THREAD

**Issue by autopoiesis3004** [Velir/dbt-ga4#108]
I am a total beginner with DBT and have a problem with the custom parameter configuration.
The custom parameters only show up in the nested column of the custom events so far.

I have tried to add some custom parameter columns for some custom events to the event tables but they don't show up.

To achieve this, I have added the parameters to the dbt_project_yml in this way:

customeventname:
    - name: "custom_parameter_1"
      value_type: "string_value"
    - name: "custom_parameter_2"
      value_type: "int_value" 

Any advice?

**Comment by dgitis** [comment]
The custom parameters supported in this package work with GA4's standard and recommended events.

For custom parameters to work with custom events, you need to create a staging model that supports the custom parameters added in dbt_project.yml.

To create a staging model for a custom event, I copy the [stg_ga4__event_scroll ](https://github.com/Velir/dbt-ga4/blob/main/models/staging/ga4/events/stg_ga4__event_scroll.sql)to a file in the main project names stg_ga4__event_customeventname.sql and then so a find and replace CTRL+F searching for 'scroll' a replacing with 'customeventname'. This is what you should get in stg_ga4__event_customeventname.sql.

```
 with customeventname_with_params as (
   select *,
      {{ ga4.unnest_key('event_params', 'percent_customeventnameed', 'int_value') }}
      {% if var("default_custom_parameters", "none") != "none" %}
        {{ ga4.stage_custom_parameters( var("default_custom_parameters") )}}
      {% endif %}
      {% if var("customeventname_custom_parameters", "none") != "none" %}
        {{ ga4.stage_custom_parameters( var("customeventname_custom_parameters") )}}
      {% endif %}
 from {{ref('stg_ga4__events')}}    
 where event_name = 'customeventname'
)

select * from customeventname_with_params
```

From here you have two options to add your custom parameters to your custom event models.

1. Unnest your custom parameters in this model.
2. Use the dbt_project.yml variables to set the custom event custom parameters.

This line shows how to do unnest custom parameters in this model.

`{{ ga4.unnest_key('event_params', 'percent_customeventnameed', 'int_value') }}`

You'll need to repeat that line for each custom parameter, change the second parameter, 'percent_customeventameed' to match the name of the custom parameter, and ensure the third parameter, 'int_value' matches the column in BigQuery that populates the data.

To use the dbt_project.yml, you'll need to delete the unnest line above and ensure that these lines are included in the staging models.

```
      {% if var("customeventname_custom_parameters", "none") != "none" %}
        {{ ga4.stage_custom_parameters( var("customeventname_custom_parameters") )}}
      {% endif %}
```

Then, presuming your dbt_project.yml file is configured properly, you should see custom parameters associated with your custom events.

This creates a staging model. You'll probably want to add a data mart for the custom event, materialize it as a table, and then copy whichever fields people actually want to report to the data mart.

**Comment by autopoiesis3004** [comment]
Thanks a lot Damon - works like a charm :-)

**Comment by Sgiostra-BitBang** [comment]
Hi @dgitis,
I've a problem with custom parameters.   

I wish to have the details of event **purchase**, so I added:
```
    purchase_custom_parameters:
      - name: "value"
        value_type: "float_value"
      - name: "currency"
        value_type: "string_value"
      - name: "transaction_id"
        value_type: "string_value"
```

in
```
vars:
  ga4:
```
of _dbt_project.yml_

I also added the file **staging/stg_ga4__event_purchase.sql** in **models**, made in this way:
```SQL
 with purchase_with_params as (
   select *,
      {% if var("purchase_custom_parameters", "none") != "none" %}
        {{ ga4.stage_custom_parameters( var("purchase_custom_parameters") )}}
      {% endif %}
 from {{ref('stg_ga4__events')}}    
 where event_name = 'purchase'
)

select * from purchase_with_params
```

At end I have the view *+stg_ga4__event_purchase**, but in the view i don't see the columns that i signed in **purchase_custom_parameters**.

And don't understand the cause of the issue.

Thanks

**Comment by dgitis** [comment]
> I also added the file staging/stg_ga4__event_purchase.sql in models, made in this way:

The issue is that you added the staging model to the project, but the variable `purchase_custom_parameters` variable is in package scope.

There are two fixes. First, since you've already created a staging model, you could change the scope of the variable.

Instead of this:

```
vars:
  ga4:
```
You should have 

```
vars:
  my_project_name:
    purchase_custom_parameters:
```

The project name is set at the top of the `dbt_project.yml` file.

Alternately, you can drop the purchase model from your project and use the purchase staging model from the package.

Just add this to your `dbt_project.yml` file:

```
models:
  ga4:
    staging:
      ga4:
        recommended_events:
          stg_ga4__event_purchase:
            +enabled: true
```

Check `/models/staging/ga4/recommended_events/` to see what other events already have staging models and also the [README ](https://github.com/Velir/dbt-ga4/blob/main/models/staging/ga4/recommended_events/README.md)there for more information on recommended events.
