### ISSUE TITLE
Last non-direct attribution

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#110]
I have this as a client requirement so I'll be working on this soon. Either I'm missing something, or it's a surprisingly complicated problem so I wanted to give others a chance to weigh in.

I see three basic approaches to this problem:

1. We do last non-direct in a View that sits on top of the session marts**and only lookup the last non-direct session within the partitions being queried**. This is efficient but has some obvious data quality flaws.
2. We lookup the last non-direct session while building the session marts. The data quality in this case will be much better but it will be horribly inefficient on large sites as it requires a lookup that we may not be able to constrain by partitions.
3. We offload last non-direct to the client and add `last_non_direct_source`, `last_non_direct_medium` and `last_non_direct_campaign` parameters and use those to define `last_non_direct_channel_grouping` and filter all of those parameters up to the session models. This suffers from some data quality issues in that cookies can be deleted and it only works at the client level (not the user level) without using lookups that compromise any efficiency gains.

The second option is the one that I find superficially most attractive, but the more I think about the details of that implementation, the less practical I think it is.

If we were to lookup the sessions table on user_key to find the last non-direct session, we would create a circular dependency with the sessions table referencing the sessions table. 

We could store the last non-direct session attribution values in the user table. 

At first I thought this would be enough, but then I realized that all of that users' sessions would change to the most recent non-direct session when a user has a new non-direct session. 

So, we could store the last non-direct session values in the user table, and then lookup that value when building the session tables.

This would mostly work when running daily builds. But what happens when a user has two different non-direct sessions in a day (with direct sessions in between)? And also what happens when we do a full-refresh on the data warehouse?

Given the problems with these two approaches, the only solution I can see is to create a new table for storing non-direct sessions (`timestamp`, `user_key`,  `last_non_direct_source`, `last_non_direct_medium`, `last_non_direct_campaign`, and `last_non_direct_channel_grouping`). This will still be a pretty beefy table on large sites, but it will work.

I feel like there's a more elegant solution that I'm missing.

If anyone can think of a better approach, I'd love to hear of it. Otherwise, what approach do you prefer? Did I miss any issues or advantages? @adamribaudo-velir @willbryant

**Comment by adamribaudo-velir** [comment]
I think I'm missing something: attribution for what? Each conversion they've configured? 

Could you provide your ideal output table schema? That would help me understand I think.

**Comment by dgitis** [comment]
Ideally, it would be something added to all `stg_ga4__event_*` models and `dim_ga4__sessions`.

**Comment by adamribaudo-velir** [comment]
I hadn't considered `dim_ga4__sessions`. Presumably if you calculate it there, and each event links to a session, then you can always find the last non-direct acquisition source from any event. 

`dim_ga4__sessions` is already inefficient so it's hard to compare. It seems fairly straight forward to create a window function on top of `stg_ga4__sessions_traffic_sources` that finds the `last_value` `default_channel_grouping` (and other fields) while ignoring nulls and `(direct)`

My stance (for better or worse) has been to add the feature first, then consider incremental strategies after. At least then we have some progress and can understand the challenge a bit better.

**Comment by adamribaudo-velir** [comment]
Wait, sorry, it's not that easy. You would need the `last_value` up until the time of the event. And that needs to be calculated for each event independently. I don't think this can be calculated as one pass through `dim_ga4_sessions` and I have a feeling that calculating this for every event is impractical.

I was reminded that Google only calculates attribution for conversions, not all events. There's probably a reason for that.

**Comment by dgitis** [comment]
I'm also reminded that UA had a setting that let you define how far back you were willing to look before a direct session was defined as a direct session.

I'm thinking we replicate this, possibly with in a View between `base_ga4__events` and `stg_ga4__events` or, preferably, parallel to `stg_ga4__events` that gets the last non-direct source / medium and before feeding it into the channel definition models. That leaves the performance tradeoffs of the window function to the user and ensures that the window function won't query the entire partition.

Instead of adding it directly to each `stg_ga4__event_*` model, we just add it do the `dim_ga4__sessions` model and then let users union the session model by `session_key` if they want last, non-direct on an event model.

**Comment by willbryant** [comment]
Not sure that I have any bright ideas that you haven't thought of already, but I do do this in my project, where I ended up writing custom session tables (plural - I need multiple stages to glue together Firebase & web sessions, etc.).

In one of the stages I'm doing

```
FIRST_VALUE(DATE_ADD((CASE WHEN source IS NOT NULL THEN event_date_dt END), INTERVAL 90 DAY) IGNORE NULLS) OVER (session_window) AS session_attribution_cutoff```

and then in a subsequent stage

```
-- we're basically doing our own version of the traffic_source attribution that GA4 provides.
-- the main reason is that they don't report the utm_content anywhere, which unfortunately we need
-- as older ad campaigns had completely generic campaign names shared across several campaigns.

add_last_non_direct_attribution AS (
  SELECT
    * EXCEPT (session_attribution_cutoff),
    (CASE WHEN session_start_date < LAST_VALUE(session_attribution_cutoff IGNORE NULLS) OVER (user_sessions_window) THEN LAST_VALUE(session_source IGNORE NULLS) OVER (user_sessions_window) END) AS attributed_source,
    (CASE WHEN session_start_date < LAST_VALUE(session_attribution_cutoff IGNORE NULLS) OVER (user_sessions_window) THEN LAST_VALUE(session_source_category IGNORE NULLS) OVER (user_sessions_window) END) AS attributed_source_category,
    (CASE WHEN session_start_date < LAST_VALUE(session_attribution_cutoff IGNORE NULLS) OVER (user_sessions_window) THEN LAST_VALUE(session_medium IGNORE NULLS) OVER (user_sessions_window) END) AS attributed_medium,
    (CASE WHEN session_start_date < LAST_VALUE(session_attribution_cutoff IGNORE NULLS) OVER (user_sessions_window) THEN LAST_VALUE(session_campaign IGNORE NULLS) OVER (user_sessions_window) END) AS attributed_campaign,
    (CASE WHEN session_start_date < LAST_VALUE(session_attribution_cutoff IGNORE NULLS) OVER (user_sessions_window) THEN LAST_VALUE(session_content IGNORE NULLS) OVER (user_sessions_window) END) AS attributed_content,
    (CASE WHEN session_start_date < LAST_VALUE(session_attribution_cutoff IGNORE NULLS) OVER (user_sessions_window) THEN LAST_VALUE(session_term IGNORE NULLS) OVER (user_sessions_window) END) AS attributed_term,
  FROM
    add_device_or_user_pseudo_id
  WINDOW
    user_sessions_window AS (PARTITION BY device_or_user_pseudo_id ORDER BY session_start_timestamp ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
),
```

The biggest problem is that it requires a pretty major cross-partition re-sort - this week it started erroring out when bigquery ran out of sort memory because I was doing the above and a couple of other different windowing operations (with different partitioning) in the same table build, so I had to add another intermediary.

I'm still trying to think of a good way to do it incrementally; it feels like that should be possible, it's just awkward because of the way sessions can spill over partitions and won't necessarily have the same "real user" IDs, which is what I'm trying to join across rather than just pseudo-IDs.

If you just want to do it over pseudo-IDs I think you should get on fine so probably easier for you without my Firebase + web shenanigans.

**Comment by dgitis** [comment]
Thank you. I thought I had the concept worked out adequately in our earlier discussions, but I actually worked on implementing this yesterday and today and found it to be much harder than I anticipated. I'll play with these ideas tomorrow.

I asked on the dbt Slack in [this thread](https://getdbt.slack.com/archives/C0VLZPLAE/p1675296663376039). The answer I got seems legit and I spent some quality time with BigQuery docs on window functions (which is more painful than it should be) to adapt the answer to BQ. I moved the limiting of partitions to the last x number of days to an earlier model to reduce the number of partitions scanned.

These are the lines that I ended up with in `stg_ga4__session_traffic_sources`:
```
session_source as (
  select    
    session_key,
    ifnull( first_value( source ignore nulls ) over (partition by user_key order by unix_micros(timestamp_micros(event_timestamp)) range between 30 preceding and current row), '(direct)') as session_source,
    ifnull( first_value( medium ignore nulls ) over (partition by user_key order by unix_micros(timestamp_micros(event_timestamp)) range between 30 preceding and current row), '(none)') as session_medium,
    ifnull( first_value( campaign ignore nulls ) over (partition by user_key order by unix_micros(timestamp_micros(event_timestamp)) range between 30 preceding and current row), '(direct)') as session_campaign,
    ifnull( first_value( nullif(default_channel_grouping, 'Direct' ) ignore nulls ) over (partition by user_key order by unix_micros(timestamp_micros(event_timestamp)) range between 30 preceding and current row), 'Direct') as default_channel_grouping
  from set_default_channel_grouping
)
```
I ended up with more total sessions when compared with the original calculation which I believe to be a result of `campaign` being null where `source` and `medium` were not.

Even if the above approach were to work, the `campaign` field would keep looking back until it finds a campaign rather than stop when source or medium are populated so I think this has to be a subquery that gets the last position where source is populated and then copies/calculates `source`, `medium`, `campaign` and `default_channel_grouping` from there.

I'm also working on the assumption that last, non-direct attribution will replace last-touch attribution. If anyone here thinks this needs to be an option or run in parallel, then speak up.

**Comment by willbryant** [comment]
Yes, I believe you'll want the same thing re null campaigns. Mine looks like this:

```
FIRST_VALUE((CASE WHEN source <> '(direct)' THEN COALESCE(campaign, '(none)') END) IGNORE NULLS) OVER (session_window) AS campaign,
```

I don't think we can make everyone happy, there probably will need to be options at some point, but I don't think you need to do all that now.

FWIW I ended up finding the *first* non-direct attribution per session and then taking the *last* non-direct attribution across sessions prior to conversion events of interest. I don't think it was a major thing but there were some sessions where it seemed the click data had some weird stuff after the initial events; I'm not sure why. Hopefully you don't need to go there.

**Comment by willbryant** [comment]
BTW AFAIK BigQuery doesn't have `RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW` which is why I did it myself using an explicit date addition and a LAST_VALUE over the whole range.

But I guess you could equally use LAST_VALUE over a 30 (90 for me) row range as well as a date test.

**Comment by dgitis** [comment]
Our current code is already getting last, non-direct session. I don't know when we changed this. I certainly don't remember a PR request explicitly fixing this portion of attribution.

```
session_source as (
    select    
        session_key,
        COALESCE(FIRST_VALUE((CASE WHEN source <> '(direct)' THEN source END) IGNORE NULLS) OVER (session_window), '(direct)') AS source,
        COALESCE(FIRST_VALUE((CASE WHEN source <> '(direct)' THEN COALESCE(medium, '(none)') END) IGNORE NULLS) OVER (session_window), '(none)') AS medium,
        COALESCE(FIRST_VALUE((CASE WHEN source <> '(direct)' THEN COALESCE(source_category, '(none)') END) IGNORE NULLS) OVER (session_window), '(none)') AS source_category,
        COALESCE(FIRST_VALUE((CASE WHEN source <> '(direct)' THEN COALESCE(campaign, '(none)') END) IGNORE NULLS) OVER (session_window), '(none)') AS campaign,
        COALESCE(FIRST_VALUE((CASE WHEN source <> '(direct)' THEN COALESCE(content, '(none)') END) IGNORE NULLS) OVER (session_window), '(none)') AS content,
        COALESCE(FIRST_VALUE((CASE WHEN source <> '(direct)' THEN COALESCE(term, '(none)') END) IGNORE NULLS) OVER (session_window), '(none)') AS term,
        COALESCE(FIRST_VALUE((CASE WHEN source <> '(direct)' THEN COALESCE(default_channel_grouping, '(none)') END) IGNORE NULLS) OVER (session_window), '(none)') AS default_channel_grouping
    from set_default_channel_grouping
    WINDOW session_window AS (PARTITION BY session_key ORDER BY event_timestamp ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
)
```

The only thing I have to add to potentially add to our live code is an `attribution_window` variable to restrict the lookback to a configurable number of partitions. I think I'll close this and leave attribution window for a later date.

**Comment by dgitis** [comment]
The current code is getting the first value for the various fields within the session where the source is not null or direct.

I need to change the window to partition by `user_key` and change the sort to `desc`.
```
    WINDOW session_window AS (PARTITION BY session_key ORDER BY event_timestamp ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
```
Otherwise, this code is pretty close to the end product already.

**Comment by dgitis** [comment]
I have some thoughts on attribution based on my work on this issue that I'd like to discuss before attempting to implement.

I'm thinking that we add an `attribution_window` variable that sets the number of days that we look back. 

I think there are a  lot of potential optimizations that we could perform if we move to a defined attribution window. But these are so many that I think they deserve separate discussion after implementing last, non-direct attribution so I'd like to avoid exploring these opportunities right now.

There are several ways of implementing attribution window, but one that I'm looking at is creating an attribution staging model whose primary purpose is to limit the scope of window functions. 

```
select
  <attribution_parameters>
from stg_ga4__events
where event_date_dt > date_sub(current_date, interval {{var('attribution_window')}} day)

```
Now this doesn't work because when we rebuild the the database, it will only look in the last attribution_window days which we could fix by only enabling this on incremental builds, but it would still break if someone wanted to create a weekly job reprocessing the last 10 days to cover late-arriving hits.

My solution is to create a separate model that replicates `_dbt_max_partition` stored as a table with one value parallel to `base_ga4__events`.

`base__ga4__min_partition`:
```
{{if is_incremental() }}
  {{if var('static_incremental_days', false) = true}}
  select
    date_sub(current_date, interval var('static_incremental_days') day
  from x --can't remember how to select without a table
  {{else}}
  select
    extract(date from max(event_timestamp))
  from events_*
  {{endif}}
{{else}}
select
  {{var('start_date')}}
{{endif}}
```
This code is not correct, but it demonstrates the idea.

Then we use this model for all down-stream incremental models (reducing the number of lookups needed for `_dbt_max_partition`) as well as the attribution staging model replacing current date with this value in the date_sub.

This should simplify the coding of incremental models moving the logic to decide what partitions are being processed outside of each individual model's logic.

It's a fairly big change. I'd love to hear thoughts or concerns before I try to implement this?

**Comment by adamribaudo-velir** [comment]
I came across this blog post which covers how to build session-level last-non-direct attribution: https://tanelytics.com/ga4-bigquery-session-traffic_source/

They start by pulling source info from the first event of each session (filtering out session_start and first_visit). Then they reach back to prior sessions to find last-non-direct. 

I like @willbryant 's approach better of looking for the first event with traffic source data in the session, not the first event. However, this blog post claims that it isn't how GA4 natively works and there are some tests they point to here: https://gtm-gear.com/posts/ga4-sessions-source-medium/

<rant> so annoying that everyone has to reverse engineer what Google is doing! why can't they share docs on stuff like this </rant>

@dgitis I'd focus on implementing last-non-direct attribution with no attribution window as a first step. It will be complicated enough on its own and will add value.

**Comment by dgitis** [comment]
My previous comment didn't directly address how I planned on getting the last, non-direct session. It was more an optimization to ensure that the window functions don't jump outside of the defined window.

I prefer @willbryant's approach as well. I don't care how Google does it if we can do it better. f

The Tanelytics post is very close to what I've been playing with for the actual query. I just wasn't sure what unit preceding bound was in, so seeing confirmation that it is seconds saves me some experimentation.

'''
order by session_start range between 2592000 preceding and current row
'''

[Google's docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/window-function-calls#def_window_frame) don't specify the unit.

**Comment by willbryant** [comment]
>However, later during the session, a login event occurred, and a user id was assigned to the visitor. That messed up the reporting in GA4 and wiped the original traffic source of the session.

WTF :)

**Comment by willbryant** [comment]
It probably bears mentioning that GA4 lets you choose the attribution methodology. From the discussion we are having, I trust that we have all gone with one of the "click" models rather than the impossible-to-reproduce "data-driven" models.

But there are valid arguments for preferring first-click vs. last-click (or even for ads-preferred).

**Comment by dgitis** [comment]
My initial thought was that we'd implement last, non-direct alongside unadulterated session attribution (and Google's cookie-based user attribution).

Last, non-direct we do because that is the default view in GA4 and I get too many questions about why there are so many Direct visits.
User attribution we do because, duh.
And then, unadulterated we do to build other session models on top.

I'd love to add other attribution models, either disabled by default or moved to dbt's /analysis/ folder built on top of the session data and I do like the idea of recreating data-driven. 

 I haven't worked with them at all, so I can't say whether we can do data-driven attribution or not, but I presume that dbt's [Python models](https://docs.getdbt.com/docs/build/python-models) would work here.

**Comment by adamribaudo-velir** [comment]
I created https://github.com/Velir/dbt-ga4/pull/196 as a starting point for discussion. The 2nd issue mentioned seems like the hardest: combining incremental loads with a 30-day lookback window.
