### ISSUE TITLE
stg_ga4__event_purchase - fields value and tax

### ISSUE THREAD

**Issue by Sgiostra-BitBang** [Velir/dbt-ga4#114]
On the definition of the view **stg_ga4__event_purchase** that are in the file: "dbt_packages/ga4/models/staging/ga4/recommended_events/stg_ga4__event_purchase.sql" the fields: **value** and **tax** are defined as **float_value** instead in the **event** table of GA4 schema in BQ they are **double_value**.
To check it You can use this query: 
```SQL
select ep.* from `<bq_project>.<analytics_ana_id>.events_*`
 cross join unnest(event_params) ep
 where event_name = 'purchase'
 and key in ('tax', 'value')
limit 100
```

As workaround i put the code of the view in the root models/staging directory of the my DBT project and replace the type of these 2 field (_value_, _tax_) with **double_value**.

**Comment by dgitis** [comment]
I recommend that you fix that and submit a PR request. Welcome to the club.

**Comment by Sgiostra-BitBang** [comment]
> I recommend that you fix that and submit a PR request. Welcome to the club.

As recommended by you I open this PR: https://github.com/Velir/dbt-ga4/pull/116

**Comment by Sgiostra-BitBang** [comment]
The issue is resolved from the pull [116](https://github.com/Velir/dbt-ga4/pull/116)
