### ISSUE TITLE
Use cluster on event_name field of base_ga4__events in order to reduce costs

### ISSUE THREAD

**Issue by franzoni315** [Velir/dbt-ga4#117]
Hello!

I am beginning to try this package and this is awesome! I see that the `base_ga4__events` table is already partitioned by time (`event_date_dt` field), but there are many views that depend on this table and filter it only by `event_name` (for instance `stg_ga4__event_video_start`). In order to reduce costs of BigQuery, a simple solution is to use the `cluster_by` option of the dbt's `config` statement:

```
{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'insert_overwrite',
        partition_by={
            "field": "event_date_dt",
            "data_type": "date",
        },
        partitions = partitions_to_replace,
        cluster_by=['event_name']
    )
}}
```

Maybe there could be an option, in order to allow even other clustered fields. Currently, in my company's datawarehouse, we also cluster by user id, and stream id.

**Comment by adamribaudo-velir** [comment]
Great suggestion! Do you want to open a PR?

**Comment by franzoni315** [comment]
Great!! I am eager to see the performance gains! I may post the results here after the approval of the PR.
