### ISSUE TITLE
Event parameters can be recorded as multiple data types, our unnest_keys() macro doesn't account for this

### ISSUE THREAD

**Issue by adamribaudo-velir** [Velir/dbt-ga4#129]
Flagged by a user in Measure Slack here: https://measure.slack.com/archives/CHC9RDUSG/p1676045661507979

From Simo Ahava: "If the value is numeric it ends up in the int (or double) value columns, if it’s something else then in the string column"

Currently, the unnest_keys macro only looks for values in 1 field (meaning 1 data type). 

Other BQ users have decided to use COALESCE to find the first non-null value. We should think through the ramifications.

**Comment by eliesg** [comment]
Here is a query one can use to find out which custom event parameters are affected:
```
SELECT
  ep.key,
  COUNT((CASE WHEN (ep.value.string_value) is not null THEN 1 END)) AS count_string_hits,
  COUNT((CASE WHEN (ep.value.int_value) is not null THEN 1 END)) AS count_int_hits,
  COUNT((CASE WHEN (ep.value.float_value) is not null THEN 1 END)) AS count_float_hits,
  COUNT((CASE WHEN (ep.value.double_value) is not null THEN 1 END)) AS count_double_hits

FROM `ga-integration-1xxxxxxxxx8.analytics_3xxxxxx6.events_YYYYMMDD`,
  UNNEST(event_params) AS ep

GROUP BY ep.key
ORDER BY ep.key
```
Example result below:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/31313582/218196411-f8d547a5-8787-4133-bc51-17a69b9add42.png">

**Comment by eliesg** [comment]
And a second query to dig into the values for one event parameter:
```
SELECT AS STRUCT
  COALESCE(
    value.string_value, 
    CAST(value.int_value AS STRING), 
    CAST(value.float_value AS STRING),
    CAST(value.double_value AS STRING)
  ) AS value,
  CASE
    WHEN value.string_value IS NOT NULL THEN "STRING"
    WHEN value.int_value IS NOT NULL THEN "INT64"
    WHEN value.float_value IS NOT NULL THEN "FLOAT64"
    WHEN value.double_value IS NOT NULL THEN "FLOAT64"
    ELSE NULL
  END
  AS value_type
FROM 
  `ga-integration-14xxxxxx.analytics_3xxxx.events_YYYYMMDD`,
  UNNEST(event_params)
WHERE
  key = '<my_event_parameter>'

GROUP BY value, value_type
ORDER BY value
```
Example results below:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/31313582/218197449-279ee628-c081-4d87-8971-e66c8b154f71.png">

**Comment by adamribaudo-velir** [comment]
@eliesg thanks. What I'm unclear on is what the desired result would look like. When we build the staging models, each column can only be 1 data type (obviously) so you're left with 3 options:

For each event parameter:
1.  Output 1 column per data type
2.  Convert INTs to STRING as necessary
3.  Pick 1, ignore the rest (<- this is the current state)

Option 1 seems very inconvenient for downstream processes to deal with. Option 2 makes some big assumptions. I don't hate Option 3 as it basically leaves it to the implementation to make sure that data types are consistent. 

Isn't your issue, at its root, and implementation issue if multiple data types are being inserted into 1 param?

**Comment by eliesg** [comment]
> I don't hate Option 3 as it basically leaves it to the implementation to make sure that data types are consistent.
It's not always possible to make sure that data types are consistent. You cannot always control the data type of each value recorded in a custom parameter. As seen in [my comment above](https://github.com/Velir/dbt-ga4/issues/129#issuecomment-1426346925). But I agree that it depends on each implementation. And it might not be necessary to include COALESCE in this repo, ie. in the default configuration of this repo. It can be left to each company to customize it, in case they have that issue.

**Comment by adamribaudo-velir** [comment]
Cool. What I'd like to do is update the package to dispatch the `unnest_key` macro which means that package users can override it with their own custom logic. Shouldn't take long.

**Comment by eliesg** [comment]
alright clear.

To confirm what you were saying above (it's an implementation issue) and to add up on [my previous comment](https://github.com/Velir/dbt-ga4/issues/129#issuecomment-1428326389): it's indeed not the best idea to use COALESCE for all custom parameters in **base_ga4__events.sql**, as I was saying. I was doing so in my own project, but the result was that all custom parameters were recorded as STRING downstream (since my COALESCE uses strings only). Which is obviously not what we want: we'll need to make calculations on some custom parameters, which isn't possible if they're STRING.

So what I'm thinking of doing now is to:

1⃣ list all custom parameters in event_params, and count values for each data type
```
select
  ep.key,
  COUNT((CASE WHEN (ep.value.string_value) is not null THEN 1 END)) as count_string_hits,
  COUNT((CASE WHEN (ep.value.int_value) is not null THEN 1 END))    as count_int_hits,
  COUNT((CASE WHEN (ep.value.float_value) is not null THEN 1 END))  as count_float_hits,
  COUNT((CASE WHEN (ep.value.double_value) is not null THEN 1 END)) as count_double_hits
from`ga-integration-1470646678388.analytics_322130036.events_20230201`,
  UNNEST(event_params) as ep
group by ep.key
order by ep.key
```

2⃣ for each custom parameter:
- if it has multiple data types, keep the coalesce function (status quo)
- if it has only one data type, remove the coalesce function and SELECT only that data type

3⃣ the custom parameters that still use COALESCE will still be displayed as string. If we need them to be recorded as another data type, add a final CTE to **base_ga4__events.sql**, that will CAST() them into that other desired data type.

**Comment by adamribaudo-velir** [comment]
I just opened #130. My recommendation would be to overload the `unnest_key` macro and handle your custom logic there. If there is a specific event param key that uses multiple data types and must be cast to a specific data type, you can create an if/else block in the macro to handle that specific case.
