### ISSUE TITLE
dbt build error related to ga_session_number

### ISSUE THREAD

**Issue by RomainTrackAnalyse** [Velir/dbt-ga4#139]
Hello,
Error message from my side following the last commit, related to the ga_session_number.

<img width="750" alt="Capture d’écran 2023-02-26 à 09 10 55" src="https://user-images.githubusercontent.com/114260967/221399842-848dc14a-0a45-4673-b1ee-919e4f1555c1.png">

**Comment by adamribaudo-velir** [comment]
Hi, if you're pulling from the main branch, there may be breaking changes introduced. In those cases, you'll need to run a full refresh (`dbt run -f`) and perhaps update any downstream models you've created that depend on the package.

That said, I did notice today that the `ga_session_number` column name was updated in `base_ga4__events` but not `base_ga4__events_intraday` which was a mistake. I'll fix that now and link this issue.
