### ISSUE TITLE
Descriptive field names

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#147]
By default, we have kept Google's source field names intact. 

However, having used this project now on about a dozen sites and coordinated with data visualization specialists to deliver reports to end users, I realize that Google's field names are a cause for confusion.

Additionally, PR #145 changes the folder structure. I think that all name changes should go into the same release so that the people using the package only have to deal with upgrades breaking lots of things once.

Here's my list of fields that should be changed:

source, medium, campaign, term etc...  get prefixed with session_

traffic_source.* get changed to user_* and traffic_source.name gets changed to user_campaign

default_channel_grouping to be changed to session_channel 

I'd like other suggestions and then, when we've collected them, I can spin up a PR to fix all of these issues.

**Comment by adamribaudo-velir** [comment]
Love it! This will add a lot of value for users of this package. I'll pull my own list of suggestions as well. 

Impressive to hear that you've deployed this on a dozen sites!
