### ISSUE TITLE
How to use the vars start_date and static_incremental_days

### ISSUE THREAD

**Issue by Sgiostra-BitBang** [Velir/dbt-ga4#148]
Hi, 
I have two issues with the  vars of the package

- First Isuue - **start_date**
I'm trying to _compile_ the object **dbt_packages/ga4/models/staging/ga4/base/base_ga4__events.sql**
When i compile it i got this error
```
Compilation Error in rpc request (from remote system.sql) Required var 'start_date' not found in config: Vars supplied to request = { "ga4": { "conversion_events": [ "add_payment_info", "add_shipping_info", "add_to_cart", "add_to_wishlist", "begin_checkout", "generate_lead", "purchase", "refund", "remove_from_cart", "select_item", "select_promotion", "view_cart", "view_item", "view_item_list", "view_promotion" ], "dataset": "analytics_297083529", "frequency": "daily", "project": "corneliani-374310", "start_date": "20230101" } }
```
I resolved the issue with this workaround: 
I putted the variable **start_date** at first level of _vars_ (out from ga4), so the question is:
This var must be at first level or i must keep 2 copy of it?

- Second Issue - **static_incremental_days**
When I try to use this var as explained in this paragraph of the README: [Incremental Loading of Event Data (and how to handle late-arriving hits)](https://github.com/Velir/dbt-ga4#incremental-loading-of-event-data-and-how-to-handle-late-arriving-hits) i got  this **Server Error**: 
> 'str' object cannot be interpreted as an integer
`16:56:56  Unable to do partial parsing because a project config has changed`

I tryed to set the value of the parameter both as string
    `static_incremental_days: "current_date - 7"`
and not
        `static_incremental_days: current_date - 7`
And i got the same error showed before in both cases

What is the right way to set this parameter to be sure the last 7 days sharded _events\__ tables will be reprocessed every run?
Thanks.

Srefano G.

**Comment by dgitis** [comment]
If you override models in your project, it's fairly easy to miss that you need to move the package variable to the project. It looks like you have that sorted, though, so good job there.

`static_incremental_days` should be an integer, just as the error message is telling you. So you want `static_incremental_days: 7`.

**Comment by Sgiostra-BitBang** [comment]
> If you override models in your project, it's fairly easy to miss that you need to move the package variable to the project. It looks like you have that sorted, though, so good job there.
> 
> `static_incremental_days` should be an integer, just as the error message is telling you. So you want `static_incremental_days: 7`.

Thanks Damon, 
now all is clear.

Stefano G.
