### ISSUE TITLE
Add 'Push Notifications' default channel

### ISSUE THREAD

**Issue by gblazq** [Velir/dbt-ga4#151]
The GA4 team has added a default channel grouping named 'Mobile Push Notifications' (https://support.google.com/analytics/answer/9756891). Given that push notifications are a common channel for content publishers, it would be a nice feature to add so that the package and the GA4 behaviour match.

At the same time, I think 'Push Notifications' is a much better channel name than 'Mobile Push Notifications', because most push notification services are not restricted to mobile devices and can send notifications to browsers on any device (for example, OneSignal is one of the most used push notification services and their own docs suggest using 'push' as the medium, no matter the device https://documentation.onesignal.com/docs/links#utm-parameters)

I have a branch ready to create a pull request with those two changes, but I had doubts on whether the channel name change was appropriate or not. Given that the default channel grouping macro does not exactly match the behaviour of GA4, I think the name change is justified, but it's also something that any end user can handle on their own. Any thoughts on this?

**Comment by adamribaudo-velir** [comment]
I'm ok with the name change based on your comments. I don't think it's reasonable for anyone to expect an exact 1:1 match between BigQuery vs. GA4 Native attribution results, so if we can provide clearer labels then that's a plus. 

Let's leave this open for a few days to see if there are other comments, though. Thanks!

**Comment by adamribaudo-velir** [comment]
Closed as part of #152
