### ISSUE TITLE
Runtime Error got an update_rpc call with an unrecognized rpc

### ISSUE THREAD

**Issue by QingSun88** [Velir/dbt-ga4#158]
Hi,
I have installed the newest version of dbt-ga4 package 3.0.0, but I meet a runtime Error showing below:
**Background steps**(before dbt run models): 
add package to packages.yml →change required variables in dbt_project.yml (data frequency: “streaming”) under the main file tree→run ‘dbt deps’  →  run ‘dbt seed’ 
**problem:**
When compile ‘base_ga4__events_intraday’, an error occurs “Runtime Error got an update_rpc call with an unrecognized rpc”, and the logs show "dbt runtime exception"

The same error also happens on these models below: 
      stg_ga4__page_conversions.sql
      stg_ga4__user_properties
      stg_ga4__session_conversions_daily
      stg_ga4__derived_session_properties

I can not find the reason and solution, and hope can get some help here.

**Comment by dgitis** [comment]
Maybe someone here can help, but I don't think this is a package issue but rather a dbt configuration issue and you're more likely to find someone who can help you with this if you cast a wider net.

I recommend you join the [dbt Slack group](https://www.getdbt.com/community/join-the-community/) and post there in either #advice-dbt-help or #dbt-cloud (if this project is on dbt Cloud).

**Comment by adamribaudo-velir** [comment]
I wonder if you're editing the right dbt_project.yml file? Can you confirm which one you're editing?

**Comment by QingSun88** [comment]
I edited two dbt_project.yml files in the dbt_packages/ga4 folder and the main parent folder. 
They can create tables/views in the BigQuery warehouse, but it shows “Runtime Error got a update_rpc call with an unrecognized rpc” when compiling and previewing these files.

**Comment by adamribaudo-velir** [comment]
Closing as this seems unrelated to the package.
