### ISSUE TITLE
Force event names to snake case

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#164]
GA4 accepts custom `event_name` values in any format. However, spaces in event names prevent YAML configurations from working on events with spaces in them.

Forcing all `event_name` values to snake case would simplify working with inconsistently named GA4 events.

**Comment by adamribaudo-velir** [comment]
Agree 100%. I had not considered that spaces in event names would break YAML config. 

Do you think a `replace(lower(event_name, ' ', '_'))` would suffice? Do we need to remove special characters?

**Comment by dgitis** [comment]
I'm sorry, but I just realized that we already do this in `base_ga4__events`. It came up in a live training session and I guess I must have looked in `stg_ga4__events` or something. I was under a time constraint, though, so I wasn't very thorough.

```
lower(replace(trim(event_name), " ", "_")) as event_name, -- Clean up all event names to be snake cased
```

That should be fine, then.
