### ISSUE TITLE
which dbt_project.yml file should be used to set optional variables?

### ISSUE THREAD

**Issue by QingFyndiq** [Velir/dbt-ga4#167]
Hi, 
It is said that optional variables can be defined  within your **dbt_project.yml** file. Here I want to ask which dbt_project.yml should be used? Is it the dbt_project.yml that located in dbt_packages/ga4 folder? Or the dbt_project.yml in the main tree parent project folder?

It would be better to specify the path of files.

Thanks.

**Comment by adamribaudo-velir** [comment]
The main, parent project folder.
