### ISSUE TITLE
stg_ga4__event_page_view: fails not_null check for 'location'

### ISSUE THREAD

**Issue by johanvdlaak** [Velir/dbt-ga4#169]
We've been running dbt with dbt-ga4 on version 1.0.0 in production for a while now, but recently (March 23rd) one of the tests started failing.

We've opted for updating to the latest version of dbt-ga4, but see the same test failure on the latest (3.1.0) version.

The test output (after a dbt run with full refresh):
```
(env)  ± dbt test -s ga4
12:20:29  Running with dbt=1.3.1
12:20:31  Found 578 models, 7474 tests, 216 snapshots, 52 analyses, 760 macros, 1 operation, 9 seed files, 582 sources, 291 exposures, 0 metrics
12:20:32  
12:20:36  Concurrency: 99 threads (target='dev')
12:20:36  
12:20:36  1 of 16 START test not_null_stg_ga4__event_page_view_page_location ............. [RUN]
12:20:36  2 of 16 START test not_null_stg_ga4__sessions_traffic_sources_session_source ... [RUN]
12:20:36  3 of 16 START test not_null_stg_ga4__user_id_mapping_user_pseudo_id ............ [RUN]
12:20:36  4 of 16 START test unique_dim_ga4__sessions_session_key ........................ [RUN]
12:20:36  5 of 16 START test unique_dim_ga4__user_pseudo_ids_user_pseudo_id .............. [RUN]
12:20:36  6 of 16 START test unique_fct_ga4__sessions_daily_session_partition_key ........ [RUN]
12:20:36  7 of 16 START test unique_fct_ga4__sessions_session_key ........................ [RUN]
12:20:36  8 of 16 START test unique_fct_ga4__user_ids_user_id_or_user_pseudo_id .......... [RUN]
12:20:36  9 of 16 START test unique_fct_ga4__user_pseudo_ids_user_pseudo_id .............. [RUN]
12:20:36  10 of 16 START test unique_stg_ga4__events_event_key ........................... [RUN]
12:20:36  11 of 16 START test unique_stg_ga4__session_conversions_daily_session_partition_key  [RUN]
12:20:36  12 of 16 START test unique_stg_ga4__sessions_traffic_sources_session_key ....... [RUN]
12:20:36  13 of 16 START test unique_stg_ga4__user_id_mapping_user_pseudo_id ............. [RUN]
12:20:36  14 of 16 START test unique_stg_ga4__user_properties_user_pseudo_id ............. [RUN]
12:20:36  15 of 16 START test unique_stg_ga4__user_pseudo_id_first_last_events_user_pseudo_id  [RUN]
12:20:36  16 of 16 START test unique_stg_ga4__user_pseudo_id_first_last_pageviews_user_pseudo_id  [RUN]
12:20:37  3 of 16 PASS not_null_stg_ga4__user_id_mapping_user_pseudo_id .................. [PASS in 1.15s]
12:20:37  1 of 16 FAIL 41 not_null_stg_ga4__event_page_view_page_location ................ [FAIL 41 in 1.16s]
12:20:38  15 of 16 PASS unique_stg_ga4__user_pseudo_id_first_last_events_user_pseudo_id .. [PASS in 2.46s]
12:20:39  11 of 16 PASS unique_stg_ga4__session_conversions_daily_session_partition_key .. [PASS in 2.97s]
12:20:39  16 of 16 PASS unique_stg_ga4__user_pseudo_id_first_last_pageviews_user_pseudo_id  [PASS in 2.98s]
12:20:39  8 of 16 PASS unique_fct_ga4__user_ids_user_id_or_user_pseudo_id ................ [PASS in 3.18s]
12:20:39  14 of 16 PASS unique_stg_ga4__user_properties_user_pseudo_id ................... [PASS in 3.44s]
12:20:39  9 of 16 PASS unique_fct_ga4__user_pseudo_ids_user_pseudo_id .................... [PASS in 3.47s]
12:20:39  5 of 16 PASS unique_dim_ga4__user_pseudo_ids_user_pseudo_id .................... [PASS in 3.53s]
12:20:39  6 of 16 PASS unique_fct_ga4__sessions_daily_session_partition_key .............. [PASS in 3.56s]
12:20:40  13 of 16 PASS unique_stg_ga4__user_id_mapping_user_pseudo_id ................... [PASS in 4.40s]
12:20:40  4 of 16 PASS unique_dim_ga4__sessions_session_key .............................. [PASS in 4.59s]
12:20:43  7 of 16 PASS unique_fct_ga4__sessions_session_key .............................. [PASS in 6.64s]
12:20:54  2 of 16 PASS not_null_stg_ga4__sessions_traffic_sources_session_source ......... [PASS in 17.97s]
12:20:59  12 of 16 PASS unique_stg_ga4__sessions_traffic_sources_session_key ............. [PASS in 22.64s]
12:20:59  10 of 16 PASS unique_stg_ga4__events_event_key ................................. [PASS in 23.35s]
12:20:59  
12:20:59  Finished running 16 tests, 1 hook in 0 hours 0 minutes and 27.70 seconds (27.70s).
12:21:00  
12:21:00  Completed with 1 error and 0 warnings:
12:21:00  
12:21:00  Failure in test not_null_stg_ga4__event_page_view_page_location (models/staging/events/stg_ga4__event_page_view.yml)
12:21:00    Got 41 results, configured to fail if != 0
12:21:00  
12:21:00    compiled Code at target/compiled/ga4/models/staging/events/stg_ga4__event_page_view.yml/not_null_stg_ga4__event_page_view_page_location.sql
12:21:00  
12:21:00  Done. PASS=15 WARN=0 ERROR=1 SKIP=0 TOTAL=16
```

I've looked for ways that we can override the tests coming in from dependencies installed via `dbt deps`, but so far haven't found a way to do that, resulting in our dbt test suite being in a red state for the last couple of days.

Not sure if something changed at Google's end, so that NULLs are now allowed for this particular field, but it looks like it.

Any ideas about the cause and/or a solution that we could implement at our end?

**Comment by adamribaudo-velir** [comment]
That's interesting. Are you accepting app events? Maybe that could be it? We can remove the not null check on page_location if Google sends null values for valid reasons. But if it helps point to an implementation error, I wouldn't want to remove it. Can you double-check your implementation?

**Comment by adamribaudo-velir** [comment]
Another option may be for us to move the test configurations to the dbt_project.yml file which, I believe, would allow them to be overwritten: https://docs.getdbt.com/reference/test-configs

**Comment by dgitis** [comment]
I had this come up on two client sites last week. For both we overrode the model and replaced `page_location` with `ifnull(page_location, 'implementation_error_null_page_location')`. For both sites, the error was traced back to implementation issues rather than package issues, hence the error message.

This lets tests pass but also increases visibility on the implementation issues.

**Comment by dgitis** [comment]
@johanvdlaak, get the code for `stg_ga4__event_page_view.sql` from the package and copy it to a model with the same name in your project's models folder (it's best to put it in a staging folder, other folders are optional but keeping your models organized is never a bad idea).

You sill need to add an except statement to the `select *` portion of that model. Depending on the version of the package that you are running, there may be already an except statement, in which case you will add 'page_location' to that except statement or you will need to add an except statement with the page location.

If there's no except statement:
```
select * except(page_location)
```
If `page_engagement_key` is already in an except statement:
```
select * except (page_engagement_key, page_location)
```

Then add a line re-setting page_location (line 3 works fine):

```
ifnull(page_location, 'implementation_error_null_page_location') as page_location,
```

**Comment by johanvdlaak** [comment]
@dgitis Thanks for your help.

Applying the patch using the same filename, I was at first running into the following dbt error:
```
09:37:50  Running with dbt=1.3.1
09:37:51  Encountered an error:
Compilation Error
  dbt found two models with the name "stg_ga4__event_page_view".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when looking for ref("stg_ga4__event_page_view").
  
  To fix this, change the name of one of these resources:
  - model.ga4.stg_ga4__event_page_view (models/staging/events/stg_ga4__event_page_view.sql)
  - model.gynzy.stg_ga4__event_page_view (models/staging/gynzy-extern/ga4_overrides/stg_ga4__event_page_view.sql)
```

Which I finally was able to resolve by disabling the original version of that model in the dbt_project.yml file (for others running into this same issue):
```
...

  ga4:
    ...
    staging:
      ...
      events:
        stg_ga4__event_page_view:
          +enabled: false # 2023-04-05: disable since we patched this file because of NULL errors
...
```

**Comment by johanvdlaak** [comment]
Closing the ticket as it's resolved by patching it at our end.

**Comment by johanvdlaak** [comment]
To me it would make a lot of sense if this were to be a warning instead of an error. Especially since the problem seems to be popping up for more than just a few cases.

**Comment by willbryant** [comment]
Yeah pretty sure Google changed something.  We started getting null values around the same time, with no changes to our GA4 setup. 

What kind of implementation issues can cause the page view event to be missing the location?

**Comment by adamribaudo-velir** [comment]
Agree with setting this as a warning. I started seeing this on a very simple installation so I believe the functionality has somehow changed on Google's side. I'll implement this now and link the PR.
