### ISSUE TITLE
Add Active Users Metrics

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#174]
The Google Analytics BigQuery documentation on [how to match GA4's user metrics, which are usually active users, in BigQuery](https://developers.google.com/analytics/blog/2023/bigquery-vs-ui).

In the absence of a good reason to the contrary, I prefer to configure our metrics to match the interface as it reduces the number of awkward conversations with stakeholders and increases trust in the data.

I propose that we add `is_engaged_user` to the users models. 

Possibly, we add `engaged_users` to the pages model. The only issue with adding it to the pages model is that it adds another CTE to that model.

Alternately, I've mentioned adding a `fct_ga4__event_page_view` model for performance reasons. If we add it there, and then build the pages model from the fct table, then we can shrink the pages model a good deal. (I do realize that I still need to demonstrate the performance benefit of switching to this structure.)

**Comment by adamribaudo-velir** [comment]
From the documentation you linked:

"In the near future, the BigQuery event export data will contain an additional field (is_active_user) to flag active users directly."

So it sounds like Google will do this for us, shortly. Don't think we need to spend time on it.
