### ISSUE TITLE
Uniqueness test failing in fct_ga4__user_ids

### ISSUE THREAD

**Issue by TannerHopkins** [Velir/dbt-ga4#191]
We're seeing the `unique_fct_ga4__user_ids_user_id_or_client_key` test fail. It's only happening for one `client_key`, but that `client_key` has 3 different `stream_id` values. 

Perhaps this was an unintended effect of swapping out `user_pseudo_id` for `client_key` in [this PR](https://github.com/Velir/dbt-ga4/pull/181)? Maybe there could only be one `user_pseudo_id` per `stream_id` before, but now there can be multiple?

Regardless, I did find it interesting that it is grouping by `user_id_or_client_key` and `stream_id` in `fct_ga4__user_ids`, but then testing for uniqueness on `user_id_or_client_key` by itself:
```
select
    user_id_or_client_key,
    stream_id,
    max(is_user_id) as is_user_id,
    min(first_seen_timestamp) as first_seen_timestamp,
    ....
from user_id_mapped
group by 1, 2
```

I'm not sure if the fix would be to update the uniqueness test to take into account `stream_id` as well, or possible stop grouping by `stream_id` and instead take the min/max, similar to what is being done with `max(is_user_id) as is_user_id` above.

**Comment by dgitis** [comment]
Is it possible that you haven't rebuilt your data with the `--full-refresh` flag on since you fixed the issue in #181 ? 

Alternately, the install instructions need updating. The latest version is 3.2.1, but this is what we have in our docs right now:

```
packages:
  - package: Velir/ga4
    version: [">=3.0.0", "<3.2.0"]
```

I'll make a PR for this issue. Please let us know if this is not the source of your problem.

**Comment by adamribaudo-velir** [comment]
@TannerHopkins are you using user_ids in your project? If a user_id spanned multiple streams then the uniqueness check running on `name: user_id_or_client_key` would fail.

The uniqueness test should be on `user_id_or_client_key || stream_id` I'll update that now. Try checking out this branch: https://github.com/Velir/dbt-ga4/pull/195 and let me know the results?

**Comment by adamribaudo-velir** [comment]
I think this is my bad. I need to move the test under the `models` key, not `columns` https://docs.getdbt.com/reference/resource-properties/tests#testing-an-expression
