### ISSUE TITLE
 Can't change destination project easily

### ISSUE THREAD

**Issue by NicoGraziani** [Velir/dbt-ga4#231]
I've got several GA4 projects that my team works with and we use a single project in BigQuery to hosts each projects' extracts. We are using one `project-raw` to store raw tables and one `project-staging` to store base and staging models.
Do you know if I can specify the destination project (=`project-staging`) to create each ga4_base and ga4_staging models in ?

**Comment by adamribaudo-velir** [comment]
Yes, you can do that in your dbt_project.yml https://docs.getdbt.com/reference/model-configs#general-configurations

**Comment by adamribaudo-velir** [comment]
And just in case... setting the destination BQ project is part of the package required variables https://github.com/Velir/dbt-ga4#required-variables

**Comment by adamribaudo-velir** [comment]
Got it. Yea the +database property will help for the staging and mart models, but not the base model.

Would it meet your needs if we had 2 variables `source_project` (to be used in `src_ga4.yml` and `destination_project` (to be used in the `combine_property_data` macro)? Open to other ideas.

**Comment by NicoGraziani** [comment]
Indeed.
We were able to manually change the destination name into `combine_property_data` macro and in `src_ga4.yml` and it worked just fine. Adding these two variables will definitely help.
I’m not sure whether it’s the best design for the library, but that’s the modification we had in mind too.

**Comment by adamribaudo-velir** [comment]
Oh great. Are you aware that you can override the macro in your own project so that you can continue to pull the latest from the library repo without fear of it being overwritten?

**Comment by NicoGraziani** [comment]
Yep, that's what we did. But ideally, we would like to avoid situations where the overwritten macro becomes outdated from the one in the package.

**Comment by adamribaudo-velir** [comment]
This should be handled with #294
