### ISSUE TITLE
Database Error with user_pseudo_id on 4.0.0

### ISSUE THREAD

**Issue by Fiction000** [Velir/dbt-ga4#236]
Hi, thanks for developing the package.

After upgrading to 4.0.0, I started having errors related to user_pseudo_ids. I could confirm the issue doesn't happen with 3.2.1.
I am using frequency daily with static_incremental_days set to 3.

Error log:

02:35:18  Database Error in model fct_ga4__pages (models\marts\core\fct_ga4__pages.sql)
02:35:18    Unrecognized name: distinct_user_pseudo_ids at [87:98]
02:35:18    compiled Code at target\run\ga4\models\marts\core\fct_ga4__pages.sql
02:35:18
02:35:18  Database Error in model fct_ga4__sessions_daily (models\marts\core\fct_ga4__sessions_daily.sql)
02:35:18    Unrecognized name: user_pseudo_id at [82:10]
02:35:18    compiled Code at target\run\ga4\models\marts\core\fct_ga4__sessions_daily.sql
02:35:18
02:35:18  Database Error in model stg_ga4__sessions_traffic_sources_last_non_direct_daily (models\staging\stg_ga4__sessions_traffic_sources_last_non_direct_daily.sql)
02:35:18    Unrecognized name: client_key at [23:5]
02:35:18    compiled Code at target\run\ga4\models\staging\stg_ga4__sessions_traffic_sources_last_non_direct_daily.sql

**Comment by adamribaudo-velir** [comment]
The models you mentioned are incremental. Can you try rebuilding them with a full refresh to see if that fixes the issue?

**Comment by Fiction000** [comment]
Thank you! The issue is resolved by setting +full_refresh: true to all models under ga4.
