### ISSUE TITLE
Not having streaming enabled generates error 

### ISSUE THREAD

**Issue by cptshrk108** [Velir/dbt-ga4#249]
The intraday table is referenced in models/staging/base/base_ga4__events.sql but does not exist is streaming is not enabled. I believe this creates an error:

> 21:28:02  BigQuery adapter: Retry attempt 1 of 1 after error: BadRequest('utility-canto-321515:analytics_353415898.events_intraday_* does not match any table.')
> 21:28:03  BigQuery adapter: https://console.cloud.google.com/bigquery?project=utility-canto-321515&j=bq:US:0fb983b5-5214-477b-9fad-29ef93973d39&page=queryresults
> 21:28:03  Timing info for model.ga4.base_ga4__events (execute): 21:28:02.160846 => 21:28:03.153548
> 21:28:03  Database Error in model base_ga4__events (models/staging/base/base_ga4__events.sql)
>   utility-canto-321515:analytics_353415898.events_intraday_* does not match any table.
>   compiled Code at target/run/ga4/models/staging/base/base_ga4__events.sql

Removing the part for the intra day table fixes it for me.

**Comment by adamribaudo-velir** [comment]
Great catch. Confirming that I can recreate this issue. We removed the 'frequency' variable, so there's no way to denote whether daily or daily+streaming is enabled anymore. Will have to give this some thought.

**Comment by adamribaudo-velir** [comment]
Should be resolved in #250 if you want to take a look.
