### ISSUE TITLE
Support new is_active_user field and collected_traffic_source fields.

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#251]
@willbryant and @adamribaudo-velir

It seems that Google has just added an `is_active_user` field to the BigQuery export. Like the `collected_traffic_source` fields that we previously discussed, this isn't a feature that does anything that we don't already do.

However, there's been some [discussion on Measure Slack](https://measure.slack.com/archives/CHC9RDUSG/p1680702843873169) with some GA4 developers about how these unnested fields are more efficient when accessed frequently. 

So maybe we want to reconsider transitioning the package to use these new fields.

The big issue that I see is that we'll want to support fallbacks where, if querying partitions that pre-date the new fields, we unnest the parameters and only use the new fields on dates that support them.

**Comment by adamribaudo-velir** [comment]
Dumb question: What does `is_active_user` represent? In the docs it's:
```
Whether the user was active (True) or inactive (False) at any point in the calendar day

Included in only the daily tables (events_YYYYMMDD).
```

But why would there be an event for a user who is not active? What do "active" mean?

**Comment by dgitis** [comment]
An active user is a user with an engaged session.

However, given the need for backwards compatibility and the fact that we can calculate this ourselves using something like `count(distinct (case when session_engaged = 1 then client_key else null end))` from our sessions tables, I think maybe we close this issue.

People who want to use it can still access it in their data marts and people who have data that predates the introduction can replicate it.
