### ISSUE TITLE
Alias is not encapsulated in quotation marks

### ISSUE THREAD

**Issue by zkim4123** [Velir/dbt-ga4#268]
when unpacking custom parameters, the ailias are not encapsulated in quotation marks. If the custom parameter has special character or space in its name, this will result in errors

![image](https://github.com/Velir/dbt-ga4/assets/144267245/1f2a9731-41e4-43ac-9b29-8c27989ff984)

**Comment by adamribaudo-velir** [comment]
If the fix is as simple as adding quotes around lines 16 & 18 of `unnest_key.sql` then it makes sense to add it to the package. 

I would just want to test and confirm that the same columns aren't used elsewhere without quotes.

**Comment by adamribaudo-velir** [comment]
Closing as I'm pretty certain this can be avoided using the `rename_column` parameter. But feel free to comment if anyone disagrees.
