### ISSUE TITLE
Cannot have a large number of properties

### ISSUE THREAD

**Issue by wesleyyee** [Velir/dbt-ga4#269]
When specifying 40 properties, the query is too large. The maximum standard SQL query length is 1024.00K characters. Is there any way to work around this to allow more properties?

**Comment by adamribaudo-velir** [comment]
Congrats! You're the first to use this many properties :) 

Can you be specific about which query/model is failing? Given this edge case, I would appreciate if you could take a first pass at a PR to resolve. I'm happy to review.

**Comment by adamribaudo-velir** [comment]
Closing until more details arrive.
