### ISSUE TITLE
Default channel grouping not in line with GA4 default channel  grouping

### ISSUE THREAD

**Issue by erikverheij** [Velir/dbt-ga4#273]
Hello,

Firstly, I'd like to express my gratitude for this incredible package; it has been immensely beneficial in my work.

While reviewing default_channel_grouping.sql, I noticed that the "Paid Other" channel group, which is a default in GA4, appears to be missing. The documentation from Google Analytics for the "Paid Other" channel group is provided here: [GA4 Default Channel Groups](https://support.google.com/analytics/answer/9756891).

For reference, the "Paid Other" criteria is defined as:
Medium matches regex `^(.*cp.*\|ppc\|retargeting\|paid.*)$`

Upon further inspection, and while comparing with the GA4 documentation, I observed a few discrepancies:

- **Other Advertising:** It appears this might not be a part of GA4's default channels anymore.
- **Push Notifications:** The GA4 documentation now refers to this as Mobile Push Notifications.
- **Cross-network:** This is defined in GA4's default channels, but I couldn't locate its presence in macros/default_channel_grouping.sql.

For visual reference, please see the image provided:

![image](https://github.com/Velir/dbt-ga4/assets/3001961/ef228f20-de37-48fd-aa5f-e041bdc3fa80)

I hope these observations prove useful, and I'm eager to contribute or assist further if needed. Thank you for your continuous effort in maintaining and improving this repository.

Kind regards, Erik

**Comment by adamribaudo-velir** [comment]
Very useful! Thanks so much. Do you feel comfortable submitting a PR to resolve these discrepancies? 

It does make me wonder if Google changes these from time to time as I thought our implementation was correct as of ~6 months ago 🤔

**Comment by erikverheij** [comment]
Thanks for your reply :) I'll create a PR in the upcoming weeks!
