### ISSUE TITLE
Inconsistency between dim_ga4__sessions_daily & dim_ga4__sessions

### ISSUE THREAD

**Issue by analyst-usafacts** [Velir/dbt-ga4#279]
The source of both models is stg_ga4__events.
However, the way we calculate landing page information is different.

For dim_ga4__sessions_daily, we are using the first non-null value for a given session (excluding event_name = 'first_visit' and 'session_start') :

```
,FIRST_VALUE(page_path IGNORE NULLS) OVER (session_partition_window) AS landing_page_path
,FIRST_VALUE(page_location IGNORE NULLS) OVER (session_partition_window) AS landing_page_location
```

However, for dim_ga4__sessions, we are using the information that is coming from the first event (excluding event_name = 'first_visit' and 'session_start'):

```
with session_first_event as 
(
    select *
    from {{ref('stg_ga4__events')}}
    where event_name != 'first_visit' 
    and event_name != 'session_start'
    qualify row_number() over(partition by session_key order by event_timestamp) = 1
),
 session_start_dims as (
    select 
        session_key,
        event_date_dt as session_start_date,
        event_timestamp as session_start_timestamp,
        page_path as landing_page_path,
        page_location as landing_page,
```

The way I noticed this inconsistency is by looking at the values for sessions, and noticing a lot of NULLS on dim_ga4__sessions.

I think we should make these values consistent. This could be achieved by either using the same logic on both models, or creating dim_ga4__sessions from dim_ga4__sessions_daily.

**Comment by dgitis** [comment]
It would be a lot more efficient to build the `dim_ga4__sessions` table from the `dim_ga4__sessions_daily` table.

My personal preference when using this package is to disable the non-partitioned session models and then create a view over the daily tables that join and perform the requisite maths for sessions that stretch across partitions. But that's just my preference for how to use the package. 

If we want to keep the big, fat sessions table, then it should be built off of the daily table. I also think we should have daily user and client tables and build the final tables off of the daily tables so that large sites can easily use the data-partitioned tables for a slight loss of data accuracy but with big cost savings. 

It just makes a lot of sense to me as a pattern to follow. Maybe we can do this when we implement the new user tables that Google is now exporting. Those are partitioned by day so it should be easy to keep them day-partitioned and add non-partitioned options on top that can be disabled as preferred. 

Last that I heard, they weren't exporting complete data so we can't use those just now.

**Comment by analyst-usafacts** [comment]
@dgitis I agree with you. When you say that "you disable" the non-partitioned session models, how do you accomplish this? Do you just change the dbt run command on your job to include only specific models, or something else?

Also, I think I could create a session view from the session_daily table, but my concern is that then it could drift from this project depending on how the logic gets implemented, and then I stuck with maintaining a model very similar without taking full advantage of this package.

**Comment by adamribaudo-velir** [comment]
Agree with everything said so far. 

@analyst-usafacts I think @dgitis means setting the non-partitioned models as 'disabled' in the dbt_project.yml file. That way, users can override that setting easily in their own dbt_project.yml file to enable them. 

I also think he's suggesting that we update the package to build dim_ga4__sessions from dim_ga4__sessions_daily. We aren't suggesting that you build that in your own project.

**Comment by dgitis** [comment]
Yes, Adam is correct on both counts. My apologies for the lack of clarity.

**Comment by dgitis** [comment]
I looked at setting this up and realized a couple of things. 

First, I usually replace the `fct_ga4__sessions` model with a view. I just created [this untested branch](https://github.com/Velir/dbt-ga4/compare/main...sessions-view) to show what it would look like.

For the `dim_ga4__sessions` model I usually just disable that without a replacement.

If we were to replace it with a view, then it would look something like this.

```
{{
    config(
        materialized = 'view'
    )
}}

with session_first_vals as 
(
    select 
        * except(session_partition_key, session_partition_date, session_partition_start_timestamp)
        , session_partition_start_timestamp as session_start_timestamp
    from {{ref('dim_ga4__sessions_daily')}}
    qualify row_number() over(partition by session_key order by session_partition_start_timestamp) = 1
)
select * from session_first_vals
```

However, the qualify statement would mean that the code there would search the entire `dim_ga4__sessions_daily` table every time they used the model. 

The advantage of using qualify is a slight improvement in the data quality where people crossing country borders at midnight in mid-session or developers who turn on device emulation at midnight in mid-session get the original value. 

I don't think this is worth it.

Maybe we build the `dim_ga4__sessions` table from `dim_ga4__sessions_daily` as a table (we can the number of partitions processed by adding a `static_incremental_days + 1` constraint in a where clause on incremental loads.

It might look like this. 

```
{% set partitions_to_replace = ['current_date'] %}
{% for i in range(var('static_incremental_days') + 1) %}
    {% set partitions_to_replace = partitions_to_replace.append('date_sub(current_date, interval ' + (i+1)|string + ' day)') %}
{% endfor %}
{{
    config(
        materialized = 'table'
    )
}}

with session_first_vals as 
(
    select 
        * except(session_partition_key, session_partition_date, session_partition_start_timestamp)
        , session_partition_start_timestamp as session_start_timestamp
    from {{ref('dim_ga4__sessions_daily')}}

    qualify row_number() over(partition by session_key order by session_partition_start_timestamp) = 1
)
select * from session_first_vals
```
