### ISSUE TITLE
Keeping base_ga4__events_intraday and base_ga4__events in sync is not DRY

### ISSUE THREAD

**Issue by adamribaudo-velir** [Velir/dbt-ga4#33]
We have duplicated select statements in `base_ga4__events_intraday` and `base_ga4__events`. This is because they need to be unioned together and `base_ga4__events_intraday` needs to remain a view while `base_ga4__events` needs to remain a table. 

This has caused a few issues at this point when the statements aren't kept in sync. Generally speaking, we want to keep code DRY (don't repeat yourself) which can avoid issues. 

Any ideas for how to keep them aligned? 

One idea: Use a macro that spits out the select statement. No input parameters necessary, just have it output text.

**Comment by dgitis** [comment]
A macro seems like the only way. I'm also thinking we might want a config
macro which would go well with merging the two base_ga4 models.

[image: Damon Gudaitis, Principal at Caret Juice Marketing]

*Damon Gudaitis*
Principal, Caret Juice Marketing
www.caretjuice.com
e: ***@***.*** | p: 778-846-9248

**Comment by dgitis** [comment]
I have a fix for this issue planned in #107 which is being worked on in the multi-site branch.
