### ISSUE TITLE
handling of user scope dimensions / user properties

### ISSUE THREAD

**Issue by clemens7haar** [Velir/dbt-ga4#36]
Hello,

We're using a custom user scope dimensions in GA4 and I tried to make it available in dim_ga4__users, but it didn't work.

The reason was that the script was looking for the value in "event_params" and not in "user_properties". Now I'm wondering if it's a bug or working as planned. It could be useful to have the last value of an event parameter available as user property, even when it was not what I expected first.

The user scope dimensions was available after replacing the parameter here:

![image](https://user-images.githubusercontent.com/20857437/179711444-afbd214a-f91c-4cff-a6b0-efbb38461d8a.png)

**Comment by adamribaudo-velir** [comment]
I have a TODO to modify this, but I probably should have created an issue.  Long story short, it's working as intended, but it was built when I didn't fully understand how GA4 handled user properties. Here's what I suggest:

- Allow users to set custom user properties that pull from the `user_properties` field as you suggest.  
- Additionally, take the current implementation and call it something like `derived_user_properties` or some name that makes it clear that we are turning event params into user-scoped properties. 

Both options seem valuable and all the scaffolding is in place already to handle both use cases. Just needs some attention.

**Comment by adamribaudo-velir** [comment]
Most of the work is done, just need to include some tests: https://github.com/Velir/dbt-ga4/tree/36-handling-of-user-scope-dimensions-user-properties
