### ISSUE TITLE
re-factor code / project structure to align better with DBT ?

### ISSUE THREAD

**Issue by vibhorj** [Velir/dbt-ga4#41]
https://docs.getdbt.com/guides/best-practices/how-we-structure/1-guide-overview
- intermediate folder
- .yml file naming convention.
- defining the fact table, grain etc.

 whether its worth the efforts at this stage or is it too much over engineering to worth the effort ;)

**Comment by adamribaudo-velir** [comment]
This is almost a year old. I think we need more targeted suggestions to act on.
