### ISSUE TITLE
Uniqueness test failures on main

### ISSUE THREAD

**Issue by willbryant** [Velir/dbt-ga4#66]
Since updating to fdd19c2f13ad4fcf3b400a237a813a417617a195, the following tests are failing:

```
10:45:43  Failure in test unique_stg_ga4__users_first_last_events_user_key (models/staging/ga4/stg_ga4.yml)
10:45:43    Got 452 results, configured to fail if != 0
10:45:43  
10:45:43    compiled SQL at target/compiled/ga4/models/staging/ga4/stg_ga4.yml/unique_stg_ga4__users_first_last_events_user_key.sql
10:45:43  
10:45:43  Failure in test unique_dim_ga4__sessions_session_key (models/marts/core/core.yml)
10:45:43    Got 11 results, configured to fail if != 0
10:45:43  
10:45:43    compiled SQL at target/compiled/ga4/models/marts/core/core.yml/unique_dim_ga4__sessions_session_key.sql
10:45:43  
10:45:43  Failure in test unique_stg_ga4__users_first_last_pageviews_user_key (models/staging/ga4/stg_ga4.yml)
10:45:43    Got 15 results, configured to fail if != 0
```

**Comment by willbryant** [comment]
@adamribaudo-velir Keen to hear your thoughts on this.

In that commit you removed the uniqueness test on the events table. But these other tests still exist.

I'm not sure if this is the right direction to be going anyway?

**Comment by adamribaudo-velir** [comment]
Right, a few things are held up and waiting on a partition-friendly way to keep events unique. Using `row_number() over(partition by session_key)` negates the partition pruning and causes unnecessary scans for any model accessing `stg_ga4__events.sql`

If we can find a way to determine event uniqueness, this feels like the right direction to take. But leaving `main` in a state with failed tests isn't great, so apologies for that. 

Any ideas on event uniqueness?

**Comment by willbryant** [comment]
Is the original problem that there are duplicate deliveries of the same event, or that there is sometimes more than one session start event per session?

**Comment by willbryant** [comment]
Aargh, I'm running into #61 again, so my sessions are just not working properly at all.

Specifically, I am missing rows from the dim_ga4__sessions table corresponding to the fct_ga4__sessions and other events, because the session_start event is associated with a session_key that is based on a user_key that is sometimes based on user_pseudo_id and sometimes based on user_id (from later in the session once they've logged in). And the dim_ga4__sessions table is based on the session start events, therefore, it's affected.

I'm not sure what we need from the session_start event itself, but in any case, I think it might be time we (╯°□°)╯︵ ┻━┻ on this approach and move on with the session remodelling you started working on (#62)? The best idea I have right now is still what I suggested in https://github.com/Velir/dbt-ga4/issues/61#issuecomment-1237514454.

**Comment by willbryant** [comment]
OK, https://github.com/Velir/dbt-ga4/pull/76 should sort that, then if you're happy with merging that I can test out the change you propose here.

**Comment by adamribaudo-velir** [comment]
All set.

**Comment by adamribaudo-velir** [comment]
This is still open because #74 is still unresolved (see latest comment)

**Comment by adamribaudo-velir** [comment]
Summarizing some discussion from #74 given that it solves some, but not all issues raised here.

- We uncovered a few different scenarios where both firebase and gtag.js can produce duplicate events. Some of these scenarios can be resolved through modifications to the collection implementation, but in other cases these are system-generated events that cannot be customized. 
- 
- Ideally, events would be deduped on the way into a partitioned table and then surrogate event keys would be created on top of the deduped events. Someone will need to propose an implementation path here.
