### ISSUE TITLE
dim_ga4__sessions model relies on flaky session_start event

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#69]
It should use the sessions_first_last_pageview model instead.

**Comment by adamribaudo-velir** [comment]
@willbryant you seem to be using the session marts. Do you have an opinion here? Is the `session_start` event a useful way to define sessions if it isn't fired consistently by all browsers? Or would you rather use `session_id` + the first `page_view` event?

**Comment by willbryant** [comment]
@adamribaudo-velir I personally think that finding sessions by grouping up the session keys sounds simpler and sounder. The docs do say that the `session_start` event will sometimes get lost.

However, I have a thought regarding the suggestion to use the pageview model: this won't work for mobile app (Firebase) event streams.

So, I guess my thinking is that it would need to be based on simply all events, unless we're going to fish out pageviews + some representative mobile event stream.
