### ISSUE TITLE
session_key changes when crossing domains

### ISSUE THREAD

**Issue by 00kennedyp** [Velir/dbt-ga4#90]
I have noticed recently the my project has been failing unique session_key test.  

Looking into our data is seem to be as a result of cross domain tracking.  It seems GA4 is doing a new "session_start" event when customer are going cross domains.   Can anyone else validate this on their GA4.  

![image](https://user-images.githubusercontent.com/14915615/203181414-5ae666df-7fb5-42cb-9fd9-66b904fa1827.png)

**Comment by dgitis** [comment]
Thanks for reporting this. Have you seen PR #73 which, I believe has been merged into the new 2.0 release? 

We still haven't fixed all session uniqueness problems, but it will fix the issue described here. 

Be sure to read the new docs when implementing 2.0. We now recommend adding an actual timestamp parameter to help with uniqueness checks. The event_timestamp is the timestamp of the batch, not actually when an event actually happened so the actual timestamp should be added to make it events occurring in the same batch don't cause uniqueness problems.

**Comment by dgitis** [comment]
Actually, my bad. PR #73 won't fix this particular problem, but we are aware of the potential for duplicate events and have plans to fix them in PR #89.

**Comment by dgitis** [comment]
I think the issue here that is not on our radar is the fact that the session key changes when you cross domains.

**Comment by willbryant** [comment]
I believe what @00kennedyp is saying is that it *doesn't* change when changing domains, but you get two rows because there's two session_start events?

In my own project I have given up on the session_start based methodology and am just aggregrating by session_key to get the facts and using window functions to choose the first non-null values for the dimension fields.

**Comment by willbryant** [comment]
@dgitis Sorry I'm not seeing what you see there. The session_key looks the same to me? `QrPufNCOAHJH+FmZ6xzyLw==` on all rows.

(How would it end up different if the user_pseudo_id and ga_session_id are the same?)

**Comment by 00kennedyp** [comment]
I think PR 73 might fix my unique session issue. I will test to tomorrow and confirm.

**Comment by adamribaudo-velir** [comment]
@00kennedyp if you're stilling seeing an issue, can you provide some more information? What release of dbt-ga4 are you using? What specific test is failing?

**Comment by dgitis** [comment]
@willbryant, the partially cut-off event at the start, identified as '1st Domain' has a different session_key, but with everything else indicating that it's the same person as the other events in the screenshot.
