### ISSUE TITLE
Engagement time calculations may be badly off

### ISSUE THREAD

**Issue by dgitis** [Velir/dbt-ga4#96]
GA4 average engagement time metrics aren't even close to the values I'm seeing in `sum_engaged_time_msec` in  `fct_ga4__sessions`.

To get a better handle on time metrics in GA4, I exported the GA4 daily average values for engagement time and session duration and then ran [this query](https://gist.github.com/3v-dgudaitis/39848c6290d8fb7aad1845d60f60d8dd) against the base data to test different calculations.

My [results for two large sites are in this sheet](https://docs.google.com/spreadsheets/d/1DkNIE08qzYgu1x-dTy5__bTgoi-wL8R_KTQQng8BLD4/edit?usp=sharing).

The total engagement time as calculated in this package is consistently 1/4 that of the GA4 interface.

There are two likely explanations: 

1. Engagement time is processed data that isn't fully calculated in the streaming export even though there are some `engagement_time_msec` parameters in the GA4 streaming export.
2. Our assumptions about engagement time are wrong.

Looking at a GA4-BigQuery integration using the batch export (that I don't have permission to share), I'm actually seeing the reverse where our package is returning engagement times that are 4x the engagement time reported in GA4. However, the data varies enough day-by-day that I'd like to see more data from other sites.

**Comment by dgitis** [comment]
It would be helpful to run the query that I linked above on other sites and compare that data with what GA4 is reporting.

I also plan on asking for clarification in the Google Partners Forum but I want to wait until the holiday is over.

**Comment by adamribaudo-velir** [comment]
I did notice a small difference in the total engaged time when summing over `stg_ga4__events` and `fct_ga4__sessions`. I don't think this explains my scenario, but it reminded me that users with consent 'denied' will not appear in the `fct_ga4__sessions` mart but will appear in GA4 reporting.

**Comment by dgitis** [comment]
This appears to be a local issue and not a package issue.
